// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"oncall-agent/api/chat"
	"oncall-agent/internal/logic/sse"
)

type ControllerV1 struct {
	service *sse.Service
}

func NewV1() chat.IChatV1 {
	return &ControllerV1{
		service: sse.New(),
	}
}
